# fly.toml app configuration file generated for phonebook-snowy on 2024-11-12T20:21:43+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-snowy'
primary_region = 'ams'

[env]
  PORT = "3000" # add this

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
